=== brayansuarez2003/bibliotecaCes3/src/resources/libreria.dtd
<!ELEMENT libreria (portada,libro+)>
        <!ELEMENT portada EMPTY>
        <!ATTLIST portada portada CDATA #REQUIRED>
<!ATTLIST libreria nombre CDATA #REQUIRED >
<!ATTLIST libreria centro CDATA #REQUIRED >
        <!ELEMENT libro (titulo,autor+,editorial+,precio)>
        <!ATTLIST libro anyo CDATA #REQUIRED>
        <!ELEMENT titulo (#PCDATA)>
        <!ELEMENT autor (apellidoAutor+,nombreAutor+)>
            <!ATTLIST autor fotoAutor CDATA #REQUIRED>
            <!ATTLIST autor documento CDATA #REQUIRED>
            <!ELEMENT apellidoAutor (#PCDATA)>
            <!ELEMENT nombreAutor (#PCDATA)>
        <!ELEMENT editorial (#PCDATA)>
        <!ELEMENT precio (#PCDATA)>

=== brayansuarez2003/bibliotecaCes3/src/resources/libreria.xml
<!DOCTYPE libreria SYSTEM "libreria.dtd">
<libreria nombre="TomÃ¡s Carrasquilla" centro="poblado" >
    <portada portada="https://www.culturaydeporte.gob.es/.imaging/mte/mcd-theme/contenido-cle-mdh/dam/mcd/cultura/mc/biblioteca-cultura/portada/bookcrossing/jcr:content/bookcrossing.jpg.jpg"/>
    <libros>
        <libro anyo="2024" codigoPais="FRA">
            <titulo>TCP/IP Illustrated</titulo>
            <autor documento ="1007055117" fotoAutor="https://lamenteesmaravillosa.com/wp-content/uploads/2021/09/william-shakespeare-768x512.png">
                <apellidoAutor>stevens</apellidoAutor>
                <nombreAutor>W.</nombreAutor>
            </autor>
            <editorial>Addison-Wesley</editorial>
            <precio>65.95</precio>
        </libro>
        <libro anyo="1994" codigoPais="FRA">
            <titulo>TCP/IP Illustrated</titulo>
            <autor documento ="1007055117" fotoAutor="https://lamenteesmaravillosa.com/wp-content/uploads/2021/09/william-shakespeare-768x512.png">
                <apellidoAutor>stevens</apellidoAutor>
                <nombreAutor>W.</nombreAutor>
            </autor>
            <editorial>Addison-Wesley</editorial>
            <precio>65.95</precio>
        </libro>
    </libros>
</libreria>
